language: java
notifications:
  irc:
    channels:
      - "chat.freenode.net#arianne"
      - "chat.freenode.net#arianne-devel"
    on_success: change
    on_failure: change
    use_notice: false
    skip_join: false
before_install:
  - pip install --user codecov
#TODO: Read from the actual file instead. (build.ant.properties:test-server-ini)
before_script:
  - cp functional_tests/marauroa/clientconnect/testserver.ini server.ini
after_success:
  - codecov
