language: java
notifications:
  irc:
    channels:
      - "chat.freenode.net#arianne"
      - "chat.freenode.net#arianne-devel"
    on_success: change
    on_failure: change
    use_notice: false
    skip_join: false
before_install:
  - pip install --user codecov
after_success:
  - codecov
