#!/bin/sh
#set -x
#this scripts are probably gentoo-specific
#just set the right classpath if it doesnt work
#
JDBC_CONN=`grep CLASSPATH /usr/share/jdbc-mysql/package.env | sed 's/.*=\:*\(.*jar\)\:*/\1/g'`
JUNIT=`grep CLASSPATH /usr/share/junit/package.env | sed 's/.*=\:*\(.*jar\)\:*/\1/g'`
MARAUROA=`grep CLASSPATH /usr/share/marauroa/package.env | sed 's/.*=\:*\(.*jar\)\:*/\1/g'`
CLS_PATH=~/.marauroa/:/etc/marauroa/:$MARAUROA:$JDBC_CONN:$JUNIT

java -classpath $CLS_PATH marauroa.marauroad
