{
    "2495": {
        "hp": "31618",
        "visibility": "100",
        "outfit": "56089901",
        "xp": "60001167",
        "type": "player",
        "base_mana": "0",
        "atk_xp": "3399",
        "id": "2495",
        "karma": "116.79",
        "atk": "17",
        "teleclickmode": "",
        "height": "1",
        "level": "182",
        "def": "379",
        "dir": "4",
        "age": "83689",
        "name": "hendrikus",
        "resistance": "100",
        "last_pvp_action_time": "1.19744391E12",
        "adminlevel": "5000",
        "speed": "0.0",
        "width": "1",
        "base_hp": "32290",
        "def_item": "412",
        "def_xp": "500002992",
        "release": "0.90.1",
        "atk_item": "100",
        "y": "43",
        "x": "19",
        "bag": {
            "order": "2,3,4,5,6,7,8,9,10,11,12",
            "2": {
                "visibility": "100",
                "width": "1",
                "class": "key",
                "type": "item",
                "id": "2",
                "height": "1",
                "name": "dungeon silver key",
                "subclass": "silver",
                "resistance": "0",
                "y": "0",
                "bound": "hendrikus",
                "x": "0"
            },
            "3": {
                "infostring": "kirdneh house 44;0;an unknown owner",
                "class": "key",
                "type": "item",
                "logid": "10209",
                "id": "3",
                "persistent": "1",
                "description": "You see a private key to House 44 in Kirdneh City.",
                "name": "house key",
                "subclass": "red",
                "y": "0",
                "x": "0"
            },
            "4": {
                "visibility": "100",
                "width": "1",
                "class": "cloak",
                "type": "item",
                "logid": "10196",
                "id": "4",
                "height": "1",
                "def": "4",
                "description": "",
                "name": "dwarf cloak",
                "subclass": "dwarf_cloak",
                "resistance": "0",
                "y": "0",
                "x": "0"
            },
            "5": {
                "visibility": "100",
                "infostring": "int_kirdneh_house_44 20 18",
                "width": "1",
                "class": "scroll",
                "type": "item",
                "logid": "10203",
                "id": "5",
                "height": "1",
                "description": "",
                "name": "marked scroll",
                "subclass": "marked",
                "resistance": "0",
                "quantity": "20",
                "y": "0",
                "x": "0"
            },
            "6": {
                "visibility": "100",
                "width": "1",
                "class": "tool",
                "type": "item",
                "logid": "15481933",
                "id": "6",
                "height": "1",
                "description": "You see a fishing rod. If you find a fishing spot you can catch fish with it.",
                "name": "fishing rod",
                "subclass": "fishing_rod",
                "resistance": "0",
                "y": "0",
                "x": "0"
            },
            "7": {
                "visibility": "100",
                "infostring": "0_kalavan_city 64 17",
                "width": "1",
                "class": "scroll",
                "type": "item",
                "logid": "15481943",
                "id": "7",
                "height": "1",
                "description": "You see a kalavan city scroll, it will take you back to kalavan city.",
                "name": "kalavan city scroll",
                "subclass": "kalavan",
                "resistance": "0",
                "quantity": "1",
                "y": "0",
                "x": "0"
            },
            "8": {
                "visibility": "100",
                "width": "1",
                "class": "food",
                "frequency": "20",
                "type": "item",
                "logid": "13482416",
                "id": "8",
                "amount": "-60",
                "height": "1",
                "description": "You see a toadstool. Beware!",
                "name": "toadstool",
                "subclass": "toadstool",
                "resistance": "0",
                "quantity": "1",
                "regen": "-5",
                "y": "0",
                "x": "0"
            },
            "9": {
                "visibility": "100",
                "width": "1",
                "class": "cloak",
                "type": "item",
                "logid": "10207",
                "id": "9",
                "height": "1",
                "def": "8",
                "description": "You see a blue elf cloak +2. The material is thick and warm.",
                "name": "blue elf cloak",
                "subclass": "blue_elf_cloak",
                "resistance": "0",
                "y": "0",
                "x": "0"
            },
            "10": {
                "visibility": "100",
                "width": "1",
                "class": "food",
                "frequency": "15",
                "type": "item",
                "logid": "13478520",
                "id": "10",
                "amount": "20",
                "height": "1",
                "description": "You see a button mushroom.  It can be an ingredient, or you can eat it.",
                "name": "button mushroom",
                "subclass": "button_mushroom",
                "resistance": "0",
                "quantity": "2",
                "regen": "2",
                "y": "0",
                "x": "0"
            },
            "11": {
                "visibility": "100",
                "width": "1",
                "class": "money",
                "type": "item",
                "logid": "11714459",
                "id": "11",
                "height": "1",
                "description": "",
                "name": "money",
                "subclass": "gold",
                "resistance": "0",
                "quantity": "5606",
                "y": "0",
                "x": "0"
            },
            "12": {
                "id": "12",
                "height": "1",
                "visibility": "100",
                "description": "You see a christmas stocking. Look inside.",
                "name": "stocking",
                "width": "1",
                "subclass": "stocking",
                "class": "box",
                "resistance": "0",
                "type": "item",
                "y": "0",
                "x": "0"
            }
        },
        "rhand": {
            "13": {
                "visibility": "100",
                "width": "1",
                "class": "club",
                "type": "item",
                "logid": "10204",
                "id": "13",
                "atk": "100",
                "height": "1",
                "rate": "2",
                "def": "100",
                "description": "",
                "name": "rod of the gm",
                "subclass": "rod_of_the_gm",
                "resistance": "0",
                "y": "0",
                "x": "0"
            }
        },
        "lhand": {
            
        },
        "head": {
            
        },
        "armor": {
            
        },
        "legs": {
            
        },
        "feet": {
            
        },
        "finger": {
            
        },
        "cloak": {
            "14": {
                "visibility": "100",
                "width": "1",
                "class": "cloak",
                "type": "item",
                "id": "14",
                "height": "1",
                "def": "8",
                "description": "You see a blue elf cloak. The material is thick and warm.",
                "name": "blue elf cloak",
                "subclass": "blue_elf_cloak",
                "resistance": "0",
                "y": "0",
                "x": "0"
            }
        },
        "keyring": {
            
        },
        "trade": {
            
        }
    }
}