<?PHP	
	
/************************************************************************************************
 ***
 *** CONFIGURATION: Modify values to meet your system
 ***
 *************************************************************************************************/
/** Location of the statistics file generated by server /
$serverStatsLocation="server_stats.xml";

/** name of the game */
$gameTitle="";

/** A Logo image for the game */
$gameLogo="";

/** A 2-3 paragraphs description of the game. HTML allowed. */
$gameDescription="";

/** A screen shoot of the game. Shouldn't be bigger than 250 width. */
$gameImage="";

/** Text for the bottom of the page. Usually copyright notices. */
$footer_text='<p class="footer">&copy; 2004 Miguel Angel Blanch Lardin</p>';

/** Text for server Down and Up states */
$serverStatusString=array(
  'Server is <font color="#FF0000">DOWN</font>. Maintenance work.',
  'Server is <font color="#00FF00">up</font>. Go and play!');

/************************************************************************************************
 *** CODE:
 *** You shouldn't need to change this.
 ***
 *************************************************************************************************/

$depth=array();
$content=array();

function parseXMLFile($file, $startElementFunc, $endElementFunc)
  {
  global $depth, $content;
  
  $depth = array();
  $content= array();

  $xml_parser = xml_parser_create();

  xml_set_element_handler($xml_parser, $startElementFunc, $endElementFunc);

  if(!($fp = fopen($file, "r"))) 
    {
    die("could not open XML input");
    }

  while ($data = fread($fp, 4096)) 
    {
    if (!xml_parse($xml_parser, $data, feof($fp))) 
      {
      die(sprintf("XML error: %s at line %d",
                   xml_error_string(xml_get_error_code($xml_parser)),
                   xml_get_current_line_number($xml_parser)));
      }
    }

  xml_parser_free($xml_parser);
  }

function stats_startElement($parser, $name, $attrs) 
  {
  global $depth, $content;
  
  array_push($depth, $name);
  $content[$name]=$attrs;
  }

function stats_endElement($parser, $name) 
  {
  global $depth, $content;

  array_pop($depth);
  }


function serverStatus()
  {
  global $content, $serverStatsLocation;
  
  parseXMLFile($serverStatsLocation,"stats_startElement","stats_endElement");

  if(time()>$content["STATISTICS"]["TIME"]+60)
    {
    return false;
    }
  else
    {
    return true;
    }
  }
  
function renderServerStats()
  {
  global $content, $serverStatsLocation;
  
  parseXMLFile($serverStatsLocation,"stats_startElement","stats_endElement");
  echo '<h1>Detailed statistics</h1>';
  echo 'This server uptime is '.$content["UPTIME"]["VALUE"].'<p/>';

  echo '<table width="100%" border="0" cellspacing="0" cellpadding="0">';
  echo '<tr style="background-color: #91D4FF;"><td align="center" colspan="3"><b>Bytes managed</b></td></tr>';
  echo '<tr style="background-color: #5F72E3;"><td>Recieved</td><td>Send</td><td>GZIP saved</td><tr>';
  echo '<tr style="background-color: #5F72E3;"><td>'.$content["BYTE"]["RECV"].'</td><td>'.$content["BYTE"]["SEND"].'</td><td>'.$content["BYTE"]["SAVED"].'</td></tr>';

  echo '<tr style="background-color: #5F72E3;"><td>&nbsp;<td/><td/></tr>';
  echo '<tr style="background-color: #91D4FF;"><td align="center" colspan="3"><b>Messages managed</b></td></tr>';
  echo '<tr style="background-color: #5F72E3;"><td>Recieved</td><td>Send</td><td>Incorrect</td><tr>';
  echo '<tr style="background-color: #5F72E3;"><td>'.$content["MESSAGE"]["RECV"].'</td><td>'.$content["MESSAGE"]["SEND"].'</td><td>'.$content["MESSAGE"]["INCORRECT"].'</td></tr>';

  echo '<tr style="background-color: #5F72E3;"><td>&nbsp;<td/><td/></tr>';
  echo '<tr style="background-color: #91D4FF;"><td align="center" colspan="3"><b>Players managed</b></td></tr>';
  echo '<tr style="background-color: #5F72E3;"><td>Logins</td><td>Logouts</td><td>Timeouts</td><tr>';
  echo '<tr style="background-color: #5F72E3;"><td>'.$content["PLAYER"]["LOGIN"].'</td><td>'.$content["PLAYER"]["LOGOUT"].'</td><td>'.$content["PLAYER"]["TIMEOUT"].'</td></tr>';

  echo '<tr style="background-color: #5F72E3;"><td>&nbsp;<td/><td/></tr>';
  echo '<tr style="background-color: #91D4FF;"><td align="center" colspan="3"><b>Actions managed</b></td></tr>';
  echo '<tr style="background-color: #5F72E3;"><td>Handled</td><td>Rejected</td><td/><tr>';
  echo '<tr style="background-color: #5F72E3;"><td>'.$content["ACTION"]["ADDED"].'</td><td>'.$content["ACTION"]["INVALID"].'</td><td/>';

  echo '<tr style="background-color: #5F72E3;"><td>&nbsp;<td/><td/></tr>';
  echo '<tr style="background-color: #91D4FF;"><td align="center" colspan="3"><b>Online load</b></td><td/></tr>';
  echo '<tr style="background-color: #5F72E3;"><td>Players</td><td>Objects</td><td/><tr>';
  echo '<tr style="background-color: #5F72E3;"><td>'.$content["ONLINE"]["PLAYERS"].'</td><td>'.$content["ONLINE"]["OBJECTS"].'</td><td/>';

  echo '</table>';
  }

function renderGFXServerStats()
  {
  echo '<h1>Last 24 hours graphical representation</h1>';
  echo '<table width="100%"  border="0" cellspacing="10" cellpadding="0">';
  echo '  <tr>';
  echo '    <td>KBytes send per hour during the last 24 hours<br/><img src="query/BS_3600.png"></td>';
  echo '    <td>KBytes recieved hour during the last 24 hours<br/><img src="query/BR_3600.png"></td>';
  echo '  </tr>';
  echo '  <tr>';
  echo '    <td>Player Online per hour during the last 24 hours<br/><img src="query/PO_60.png"></td>';
  echo '    <td>Daily accounts created during last 15 days<br/><img src="query/AC_24_7.png"></td>';
  echo '  </tr>';
  echo '</table>';
  }

?>

<html>
<head>
  <title><?php echo $gameTitle; ?></title>
  <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
  <link REL="SHORTCUT ICON" HREF="favicon.ico">
  <link rel="stylesheet" type="text/css" href="cssdef.css">
  <script language="JavaScript">
	var newwindow = '';

	function popitup(url)
	  {
	  if (!newwindow.closed && newwindow.location)
	    {
	    newwindow.location.href = url;
	    }
	  else
	    {
		newwindow=window.open(url,'name','height=200,width=300');
		if (!newwindow.opener) newwindow.opener = self;
	    }
	  if (window.focus) {newwindow.focus()}
	  return false;
      }
  </script>
</head>

<body bgcolor="#CEEAF6">
<table width="100%"  border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td><table width="100%"  border="0" cellspacing="0" cellpadding="0">
      <tr align="center">
        <td><?php echo '<img src="'.$gameLogo.'" alt="game logo"/>'; ?></td>
        <td valign="center"><?php global $serverStatusString; echo (serverStatus()? $serverStatusString[1]: $serverStatusString[0]); ?></td>
        <td><a href="http://arianne.sourceforge.net"><img src="http://arianne.sourceforge.net/images/ariannePowered.png" alt="Arianne Powered!"></a></td>
      </tr>
    </table></td>
  </tr>
  <tr>
    <td>
      <table width="100%"  border="0" cellspacing="0" cellpadding="0">
      <tr valign="top">
        <td><?PHP echo '<h1>What is '.$gameTitle.'?</h1>'.$gameDescription; ?></td>
        <td width="30"/>
        <td width="300"><?php echo '<img src="'.$gameImage.'" />'; ?></td>
      </tr>
      </table>
      <p/>
      <table width="100%"  border="0" cellspacing="0" cellpadding="0">
        <tr valign="top">
          <td><?php include('account.php'); ?></td>
          <td><?php include('top20.php'); ?></td>
        </tr>
      </table>
      <h1>Downloads</h1>
      Please download from <a href="http://arianne.sourceforge.net/?arianne_url=games/game_<?PHP echo $gameTitle; ?>">Arianne</a><p/>
      <table width="100%">
        <tr valign="top">
         <td width="40%"><?php renderServerStats(); ?></td>
         <td width="60%"><?php renderGFXServerStats(); ?></td>
        </tr>
      </table>
    </td>
  </tr>
  <tr>
    <td align="right"><?php echo $footer_text; ?></td>
  </tr>
</table>
</body>
</html>
