install:
	cp marauroad $(DESTDIR)/usr/bin/marauroad	
	chown +x $(DESTDIR)/usr/bin/marauroad	
	
	mkdir -p $(DESTDIR)/opt/marauroa/libs
	cp libs/* $(DESTDIR)/opt/marauroa/libs
	
	cp README $(DESTDIR)/opt/marauroa/README