#!/bin/bash

if [ $# -eq 0 ]; then
  echo "Missing params."
  echo "Usage: $0 <game-server-plugin> <server.ini>"
  exit 1
fi

export LOCALCLASSPATH=.:libs/marauroa-3.9.2.jar:{jython_jar}:libs/h2.jar:libs/mysql-connector.jar:libs/log4j.jar
java -cp $LOCALCLASSPATH marauroa.server.marauroad -c $2
