#!/bin/bash

if [ $# -eq 0 ]; then
  echo "Missing params."
  echo "Usage: $0 <game-server-plugin> <server.ini>"
  exit 1
fi

set LOCALCLASSPATH=.:libs/marauroa-2.0.2.jar:libs/jython.jar:libs/mysql-connector.jar:libs/log4j.jar
java -cp $LOCALCLASSPATH marauroa.server.marauroad -c server.ini -l
