#!/bin/bash

if [ $# -eq 0 ]; then
  echo "Missing params."
  echo "Usage: $0 <game-server-plugin> <server.ini>"
  exit 1
fi

export LOCALCLASSPATH="$1:/opt/marauroa/libs/jython.jar:/opt/marauroa/libs/mysql-connector.jar:/opt/marauroa/libs/log4j.jar"
java -cp $LOCALCLASSPATH -jar /opt/marauroa/libs/marauroa-2.00.jar -c server.ini -l $LOCALCLASSPATH -jar /opt/marauroa/libs/marauroa-2.00.jar -c server.ini -l $LOCALCLASSPATH -jar /opt/marauroa/libs/marauroa-1.92.jar -c server.ini -l $LOCALCLASSPATH -jar /opt/marauroa/libs/marauroa-1.92.jar -c server.ini -l $LOCALCLASSPATH -jar /opt/marauroa/libs/marauroa-1.92.jar -c server.ini -l $LOCALCLASSPATH -jar /opt/marauroa/libs/marauroa-1.92.jar -c server.ini -l $LOCALCLASSPATH -jar /opt/marauroa/libs/marauroa-1.92.jar -c server.ini -l $LOCALCLASSPATH -jar /opt/marauroa/libs/marauroa-1.92.jar -c server.ini -l $LOCALCLASSPATH -jar /opt/marauroa/libs/marauroa-1.92.jar -c server.ini -l
