package marauroa.server.game;

import marauroa.common.game.RPObject;


/**
 * This class represent the result of creating an account.
 * It will also contains the generated username and the generated RPObject, so
 * we can inform client about changes on username and/or RPObject.
 * @author miguel
 *
 */
public class AccountResult {
	/** This enum represent the possible values returned by the create account process.
	 *  Caller should verify that the process ended in OK_ACCOUNT_CREATED.
	 * @author miguel
	 */
	public static enum Result {
		/** Account was created correctly. */
		OK_ACCOUNT_CREATED,
		/** Account was not created because one of the important parameters was missing. */
		FAILED_EMPTY_STRING,
		/** Account was not created because an invalid characters( letter, sign, number ) was used */
		FAILED_INVALID_CHARACTER_USED,
		/** Account was not created because any of the parameters are either too long or too short. */
		FAILED_STRING_SIZE,
		/** Account was not created because because this account already exists. */
		FAILED_PLAYER_EXISTS,
		/** Account was not created because there was an unspecified exception. */
		FAILED_EXCEPTION
	}

	/** The result of creating the account */
	private Result result;
	/**
	 *  The username generated by the create account process.
	 *  It will usually be the same that the username requested.
	 */
	private String username;
	/**
	 * Any changes done to the template by create account that could be relevant to client.
	 */
	private RPObject template;

	/**
	 * Constructor
	 * @param result the result of creating the account.
	 * @param username the username generated.
	 * @param template the RPObject template generated.
	 */
	public AccountResult(Result result, String username, RPObject template) {
		this.result=result;
		this.username=username;
		this.template=template;
	}

	/**
	 * Returns the result of creating the account
	 * @return the result of creating the account
	 */
	public Result getResult() {
		return result;
	}

	/**
	 * Returns the username generated by create account.
	 * @return the username generated by create account.
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * Returns the RPObject template generated.
	 * @return the RPObject template generated.
	 */
	public RPObject getTemplate() {
		return template;
	}
}

